Repository CharlyCst/miralis, pull requests merged in 2024-11, with the labels that each got.

#244 Start Implementing Keystone Policy
  .gitignore
  config/qemu-keystone.toml
  crates/config_select/src/lib.rs
  src/policy/keystone.rs
Labels: main

#258 Fix Keystone Create Enclave
  Cargo.lock
  Cargo.toml
  config/test/qemu-virt-test-keystone.toml
  crates/abi/src/lib.rs
  justfile
  payload/test_keystone_payload/Cargo.toml
  payload/test_keystone_payload/main.rs
  src/arch/metal.rs
  src/arch/mod.rs
  src/arch/userspace.rs
  src/policy/keystone.rs
Labels: bug

#260 Implement IPI for the protect payload policy
  src/device/clint.rs
  src/driver.rs
  src/platform/mod.rs
  src/policy/default.rs
  src/policy/keystone.rs
  src/policy/mod.rs
  src/policy/protect_payload.rs
  src/virt.rs
Labels: enhancement

#281 SailBugfix: Correct MPP Value in `mstatus` During `mret` Execution
  src/virt/csr.rs
  src/virt/emulator.rs
Labels: bug

#282 SailBugFix: Correct mvendorid to 32 bits as per RISC-V specification
  src/arch/userspace.rs
  src/virt/csr.rs
  src/virt/mod.rs
Labels: bug

#283 SailBugfix: Correct scounteren, mcountinhibit, and mcounteren to 32 b…
  src/arch/userspace.rs
  src/virt/csr.rs
  src/virt/mod.rs
  src/virt/world_switch.rs
Labels: bug

#289 SailFeature: Add support for RISC-V optional vector extension in the …
  src/arch/metal.rs
  src/arch/mod.rs
  src/arch/registers.rs
  src/arch/userspace.rs
  src/decoder.rs
  src/virt/csr.rs
  src/virt/mod.rs
Labels: enhancement, Test

#290 SailBugfix: mcycle and minstret are not read-only registers
  firmware/csr_ops/perf_counters.rs
  src/virt/csr.rs
Labels: bug

#291 SailBugfix: Restrict Mtvec to Direct or Vector Mode
  src/virt/csr.rs
Labels: bug

#292 SailBugfix: Restrict stvec to Direct or Vector Mode
  src/virt/csr.rs
Labels: bug
