Repository CharlyCst/miralis, pull requests merged in 2024-09, with the labels that each got.

#173 Decode `sfence.vma` with registers
  src/arch/metal.rs
  src/arch/mod.rs
  src/arch/userspace.rs
  src/decoder.rs
  src/main.rs
  src/virt.rs
Labels: bug

#171 Refactor config.rs to be easier to add more param
  runner/src/config.rs
Labels: enhancement

#188 Spike integration
  config/spike.toml
  crates/config_helpers/src/lib.rs
  runner/src/artifacts.rs
  runner/src/config.rs
  runner/src/run.rs
  src/config.rs
  src/platform/virt.rs
Labels: enhancement, Benchmark

#192 Integrate cargo deny in the CI / CD pipeline
  benchmark_analyzer/Cargo.toml
  crates/abi/Cargo.toml
  crates/config_helpers/Cargo.toml
  crates/config_select/Cargo.toml
  crates/core/Cargo.toml
  deny.toml
  firmware/benchmark/csr_write/Cargo.toml
  firmware/benchmark/ecall_benchmark/Cargo.toml
  firmware/breakpoint/Cargo.toml
  firmware/csr_ops/Cargo.toml
  firmware/default/Cargo.toml
  firmware/device/Cargo.toml
  firmware/ecall/Cargo.toml
  firmware/interrupt/Cargo.toml
  firmware/mcause/Cargo.toml
  firmware/mepc/Cargo.toml
  firmware/mret/Cargo.toml
  firmware/os_ctx_switch/Cargo.toml
  firmware/os_ecall/Cargo.toml
  firmware/pmp/Cargo.toml
  firmware/sandbox/Cargo.toml
  firmware/vectored_mtvec/Cargo.toml
  payload/hello_world/Cargo.toml
  runner/Cargo.toml
  src/Cargo.toml
Labels: Test

#193 Integrate Clippy (linter) in the CI/CD pipeline
  benchmark_analyzer/src/lib.rs
  crates/config_helpers/src/lib.rs
  crates/config_select/src/lib.rs
  justfile
  runner/src/artifacts.rs
  runner/src/config.rs
  runner/src/gdb.rs
  runner/src/run.rs
  src/arch/mod.rs
  src/arch/registers.rs
  src/arch/trap.rs
  src/arch/userspace.rs
  src/config.rs
  src/decoder.rs
  src/device/clint.rs
  src/device/tester.rs
  src/driver.rs
  src/logger.rs
  src/virt.rs
Labels: Test

#205 Make Miralis panic if we try to set MBE/SBE/UBE bit in mstatus
  src/virt.rs
Labels: bug

#197 Emulation of RISC-V H extension
  Cargo.lock
  Cargo.toml
  config/test/qemu-rustsbi-test-kernel-spike.toml
  config/test/qemu-rustsbi-test-kernel.toml
  config/test/qemu-virt-2harts.toml
  config/test/qemu-virt-benchmark.toml
  config/test/qemu-virt-hello-world-payload-spike.toml
  config/test/qemu-virt-hello-world-payload.toml
  config/test/qemu-virt-release.toml
  config/test/qemu-virt-sifive-u54-spike.toml
  config/test/qemu-virt-sifive-u54.toml
  config/test/qemu-virt.toml
  firmware/csr_ops/main.rs
  firmware/hypervisor/Cargo.toml
  firmware/hypervisor/main.rs
  justfile
  misc/riscv-unknown-miralis.json
  misc/riscv-unknown-unprivileged.json
  runner/src/config.rs
  src/arch/metal.rs
  src/arch/mod.rs
  src/arch/registers.rs
  src/arch/userspace.rs
  src/config.rs
  src/decoder.rs
  src/main.rs
  src/platform/mod.rs
  src/virt.rs
Labels: enhancement

#210 Check H & S mode availability at runtime
  config/example.config.toml
  config/test/qemu-rustsbi-test-kernel-spike.toml
  config/test/qemu-rustsbi-test-kernel.toml
  config/test/qemu-virt-2harts.toml
  config/test/qemu-virt-benchmark.toml
  config/test/qemu-virt-hello-world-payload-spike.toml
  config/test/qemu-virt-hello-world-payload.toml
  config/test/qemu-virt-release.toml
  config/test/qemu-virt-sifive-u54-spike.toml
  config/test/qemu-virt-sifive-u54.toml
  config/test/qemu-virt.toml
  runner/src/config.rs
  src/arch/metal.rs
  src/arch/mod.rs
  src/arch/userspace.rs
  src/config.rs
  src/decoder.rs
  src/main.rs
  src/platform/mod.rs
  src/virt.rs
Labels: bug, enhancement

#212 Save and restore S registers only if S mode is available
  src/virt.rs
Labels: bug

#208 Benchmark payload
  Cargo.lock
  Cargo.toml
  config/test/spike-virt-benchmark.toml
  firmware/tracing_firmware/Cargo.toml
  firmware/tracing_firmware/main.rs
  justfile
Labels: Test, Benchmark

#213 Add more RAM to qemu
  runner/src/run.rs
Labels: bug

#217 Bugfix: correction of emulation in HStatus
  src/arch/mod.rs
  src/virt.rs
Labels: bug

#220 Bugfix: set TVM and TSR fields of Mstatus read-only only when S-mode …
  src/virt.rs
Labels: bug

#204 Add U-boot test in the CI / CD pipeline
  config/test/qemu-virt-u-boot-payload.toml
  justfile
  misc/artifacts.toml
Labels: Test
